[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.14.0",
    "camel-tools>=1.6.0",
    "dataclasses>=0.8",
    "datasets>=5.0.0",
    "evaluate>=0.4.6",
    "huggingface-hub>=1.25.1",
    "laser-encoders>=0.0.2",
    "sacrebleu>=2.6.0",
    "sentencepiece>=0.2.2",
    "torchaudio>=2.11.0",
    "transformers>=5.14.1",
    "typing>=3.10.0.0",
]
